# Generated by Django 5.2 on 2025-04-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
